import pandas as pd
import streamlit as st

from src.predictor import load_model, predict_price


model = load_model()

st.set_page_config(
    page_title="House Price Predictor",
    page_icon="🏠",
    layout="centered",
)

st.title("🏠 House Price Prediction")
st.write(
    "Enter the property details below to estimate its market price."
)

st.subheader("Property Details")

col1, col2 = st.columns(2)

with col1:
    area = st.number_input(
        "Area (sq ft)",
        min_value=300,
        max_value=20000,
        value=5000,
        step=100,
    )

    bedrooms = st.number_input(
        "Bedrooms",
        min_value=1,
        max_value=10,
        value=3,
        step=1,
    )

    bathrooms = st.number_input(
        "Bathrooms",
        min_value=1,
        max_value=10,
        value=2,
        step=1,
    )

with col2:
    stories = st.number_input(
        "Stories",
        min_value=1,
        max_value=10,
        value=2,
        step=1,
    )

    parking = st.number_input(
        "Parking Spaces",
        min_value=0,
        max_value=5,
        value=2,
        step=1,
    )

    furnishingstatus = st.selectbox(
        "Furnishing Status",
        ["furnished", "semi-furnished", "unfurnished"],
    )

st.subheader("Property Features")

col1, col2 = st.columns(2)

with col1:
    mainroad = st.selectbox("Main Road", ["yes", "no"])
    guestroom = st.selectbox("Guest Room", ["yes", "no"])
    basement = st.selectbox("Basement", ["yes", "no"])
    prefarea = st.selectbox("Preferred Area", ["yes", "no"])

with col2:
    hotwaterheating = st.selectbox(
        "Hot Water Heating",
        ["yes", "no"],
    )
    airconditioning = st.selectbox(
        "Air Conditioning",
        ["yes", "no"],
    )

input_data = pd.DataFrame({
    "area": [area],
    "bedrooms": [bedrooms],
    "bathrooms": [bathrooms],
    "stories": [stories],
    "mainroad": [mainroad],
    "guestroom": [guestroom],
    "basement": [basement],
    "hotwaterheating": [hotwaterheating],
    "airconditioning": [airconditioning],
    "parking": [parking],
    "prefarea": [prefarea],
    "furnishingstatus": [furnishingstatus],
})

if st.button(
    "Predict House Price",
    type="primary",
    use_container_width=True,
):
    try:
        prediction = predict_price(model, input_data)[0]

        st.success(
            f"Estimated House Price: ₹{prediction:,.2f}"
        )

        st.caption(
            "This estimate is generated by the trained machine learning model "
            "and should not be treated as a guaranteed market price."
        )

    except Exception:
        st.error(
            "Unable to generate a prediction. "
            "Please check the entered values and try again."
        )
